builders:
  embedded_config:
    import: "./lib/embedded_config.dart"
    builder_factories: ["configBuilder"]
    build_extensions: {".dart": [".embedded.dart"]}
    build_to: source
    auto_apply: root_package
